# docker-compose.yml文件的版本
version: "3.7"
# 管理的服务
services:
  photoalbum:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        JAR_FILE: /target/photoalbum.jar
    restart: always