server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
alibaba:
  oss:
    accessKeyId: LTAI4Fd66vvuVj31seQ2YbQQ
    accessKeySecret: AgUkSMWtlICI7lY2oBFM0aD94ZlqYt
    endpoint: oss-cn-beijing.aliyuncs.com
    bucketName: attach-mango
    httpPrefix: https://
    cdnHost: photoalbum.517cdn.com
  ots:
    accessKeyId: LTAI4Fd66vvuVj31seQ2YbQQ
    accessKeySecret: AgUkSMWtlICI7lY2oBFM0aD94ZlqYt
    endPoint: https://table-mango.cn-hangzhou.ots.aliyuncs.com
    instanceName: table-mango
  mns:
    accessKeyId: LTAI4Fd66vvuVj31seQ2YbQQ
    accessKeySecret: AgUkSMWtlICI7lY2oBFM0aD94ZlqYt
    endpoint: https://1948640781844768.mns.cn-hangzhou.aliyuncs.com