alibaba:
  acm:
    file-extension: yml
    endpoint: acm.aliyun.com
    namespace: 76e49807-6836-455f-bb2d-dd2e912ef393
    accessKey: LTAI4Fd66vvuVj31seQ2YbQQ
    secretKey: AgUkSMWtlICI7lY2oBFM0aD94ZlqYt
    group: photoalbum